### ISSUE TITLE
Display alerts/notifications for upcoming Events

### ISSUE THREAD

**Issue by halalak** [peschkaj/todo.hs#10]
- [ ] allow user to define how far before start time to be notified about an upcoming Event 
- [ ] display all Events that meet the above criteria

_will the program continuously check the saved Events and display as Events come up?_

**Comment by peschkaj** [comment]
See my comment on #3 for how we can accomplish this.

**Comment by peschkaj** [comment]
I _think_ we can close this now that we have the web UI working...

**Comment by halalak** [comment]
Yeah, if you already have it working with the web UI then this can be closed!
