### ISSUE TITLE
Display alerts for upcoming deadlines

### ISSUE THREAD

**Issue by peschkaj** [peschkaj/todo.hs#3]
- [x] read deadlines from Deadline file
- [x] filter deadlines within time frame
- [x] sort by due date
- [x] display filtered deadlines

**Comment by halalak** [comment]
Will the alert only show up if the user requests to see all Deadlines that are coming up within x amount of time? Or will there be a automated timer that handles displaying the alerts?

**Comment by peschkaj** [comment]
If we can get `brick` working, it has facilities for automated timers. Looking at [Samuel Tay's brick tutorial](https://github.com/jtdaugherty/brick/blob/master/docs/samtay-tutorial.md) we should be able to set up an app that has a tick called every `x` seconds. In the absence of user input, we can check for upcoming events either every tick or do something like the promotion timer in xv6 and check every `n` app ticks to see if there are upcoming events.

**Comment by halalak** [comment]
I guess that would have to fall under a feature that can be implemented only if we meet our stretch goal
