### ISSUE TITLE
Display all events and deadlines

### ISSUE THREAD

**Issue by peschkaj** [peschkaj/todo.hs#6]
- [x] display all events and deadlines
- [x] sort them all together

**Comment by halalak** [comment]
Have you had the chance to test this out? Any recommendations on what should be changed?

**Comment by halalak** [comment]
Yeah, I think if we wanted to incorporate it into the front-end it would definitely require some time (that we don't have). However, we should still keep it in the project just as an extra functionality that can potentially be incorporated to the web page. I'll go ahead and do some more tests as well, and see if I catch any bugs I may have missed on the first round of testing.
